version: "3.8"

services:
  postgres_aiscribe:
    image: postgres:14
    container_name: postgres_aiscribe
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aiscribe
    ports:
      - "5433:5432"
    volumes:
      - pgdata_aiscribe:/var/lib/postgresql/data

volumes:
  pgdata_aiscribe:
